<?php
$title = "Financial Report";
include 'head.php';

// Database connection
try {
    $pdo = new PDO("mysql:host=localhost;port=3307;dbname=finance", "root", "");
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

$stmt = $pdo->query("SELECT * FROM report ORDER BY id DESC LIMIT 1");
$report = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$report) {
    die("No report data found.");
}
$stmt = $pdo->query("SELECT * FROM pangalawa ORDER BY id DESC LIMIT 1");
$pangalawa = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$pangalawa) {
    die("No table data found.");
}
$stmt = $pdo->query("SELECT * FROM totals ORDER BY id DESC LIMIT 1");
$totals = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$totals) {
    die("No table data found.");
}
?>

<section class="content" style="padding: 1rem;">
  <article class="module-content"></article>

  <div class="tabs">
    <div class="tab">Monthly</div>
    <div class="tab">Annual</div>
  </div>

  <div class="date-picker">
    <label for="from">From:</label>
    <input type="date" id="from" name="from">
    <label for="to">To:</label>
    <input type="date" id="to" name="to">
  </div>

  <div class="kpi-cards">
    <?php if ($totals): ?>
    <div class="card">Total Collected: ₱<?= number_format($totals['t.collected']) ?></div>
    <div class="card">Total Due: ₱<?= number_format($totals['t.due']) ?></div>
    <div class="card">Total Scholarships Awarded: ₱<?= number_format($totals['t.scholar']) ?></div>
    <div class="card">Total Refunds: ₱<?= number_format($totals['t.refund']) ?></div>
    <?php else: ?>
    <div class="card">No data available</div>
    <?php endif; ?>
  </div>

  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>Collected</th>
        <th>Due</th>
        <th>Scholarships</th>
        <th>Refunds</th>
      </tr>
    </thead>
    <tbody>
      <?php if ($pangalawa): ?>
        <tr>
          <td><?= date("F", strtotime($pangalawa['month'])) ?></td>
          <td>₱ <?= number_format($pangalawa['collected']) ?></td>
          <td>₱ <?= number_format($pangalawa['due']) ?></td>
          <td>₱ <?= number_format($pangalawa['scholarship']) ?></td>
          <td>₱ <?= number_format($pangalawa['refund']) ?></td>
        </tr>
      <?php else: ?>
        <tr>
          <td colspan="5">No data available</td>
        </tr>
      <?php endif; ?>
    </tbody>
  </table>

  <?php if ($report): ?>
  <div class="detail-view">
    <h3>Report Details</h3>
    <p><strong>Report Period:</strong>
      <?= date("F j, Y", strtotime($report['period_from'])) ?> - <?= date("F j, Y", strtotime($report['period_to'])) ?>
    </p>
    <p><strong>Report Type:</strong> <?= htmlspecialchars($report['report_type']) ?></p>
    <p><strong>Summary:</strong> <?= nl2br(htmlspecialchars($report['summary'])) ?></p>
    <p><strong>Generated By:</strong> <?= htmlspecialchars($report['generated_by']) ?></p>
  </div>
  <?php else: ?>
  <div class="detail-view">
    <p>No report data available.</p>
  </div>
  <?php endif; ?>

</section>

<?php include 'nav/footer.php'; ?>
