  <section class="content">
    <article class="module-content"></article>
  <div class="tabs">
    <div class="tab">Monthly</div>
    <div class="tab">Annual</div>
  </div>

  <div class="date-picker">
    <label for="from">From:</label>
    <input type="date" id="from" name="from">
    <label for="to">To:</label>
    <input type="date" id="to" name="to">
  </div>

  <div class="kpi-cards">
    <div class="card">Total Collected: ₱120,000</div>
    <div class="card">Total Due: ₱30,000</div>
    <div class="card">Total Scholarships Awarded: ₱50,000</div>
    <div class="card">Total Refunds: ₱10,000</div>
  </div>



  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>Collected</th>
        <th>Due</th>
        <th>Scholarships</th>
        <th>Refunds</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>January</td>
        <td>₱30,000</td>
        <td>₱5,000</td>
        <td>₱10,000</td>
        <td>₱2,000</td>
      </tr>
      
    </tbody>
  </table>

  <div class="detail-view">
    <h3>Report Details</h3>
    <p><strong>Report Period:</strong> January 1 - January 31, 2025</p>
    <p><strong>Report Type:</strong> Monthly</p>
    <p><strong>Summary:</strong> Total transactions reviewed include collections, dues, scholarships, and refunds for the month of January.</p>
    <p><strong>Generated By:</strong> Finance Admin</p>
  </div>
</section>
<?php include 'footer.php'; ?>